name: Test favicon
on:
  push:
    branches: ["fix/search-favicon"]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: fix/search-favicon
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: python src/test_favicon.py
